spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  quartz:
    wait-for-jobs-to-complete-on-shutdown: false
    job-store-type: jdbc
    overwrite-existing-jobs: true
    jdbc:
      initialize-schema: always
    properties:
      org.quartz.jobStore.isClustered: true
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.scheduler.skipUpdateCheck: true
      org.quartz.threadPool.threadCount: 2
      # org.quartz.plugin.triggHistory.class: org.quartz.plugins.history.LoggingTriggerHistoryPlugin
      # org.quartz.plugin.jobHistory.class: org.quartz.plugins.history.LoggingJobHistoryPlugin


  datasource:
    # url: jdbc:mariadb://localhost:3306/sys
    # username: root
    # password: my-quartz_pass
    url: jdbc:h2:file:./quartz-db
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2