// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/test_message.proto

package org.sterl.proto;

public final class TestMessage {
  private TestMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.RequestMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .tutorial.RequestMessage.MessageType type = 1 [default = MOVE];</code>
     */
    boolean hasType();
    /**
     * <code>required .tutorial.RequestMessage.MessageType type = 1 [default = MOVE];</code>
     */
    org.sterl.proto.TestMessage.RequestMessage.MessageType getType();

    /**
     * <code>optional .tutorial.MoveData moveData = 2;</code>
     */
    boolean hasMoveData();
    /**
     * <code>optional .tutorial.MoveData moveData = 2;</code>
     */
    org.sterl.proto.TestMessage.MoveData getMoveData();
    /**
     * <code>optional .tutorial.MoveData moveData = 2;</code>
     */
    org.sterl.proto.TestMessage.MoveDataOrBuilder getMoveDataOrBuilder();

    /**
     * <code>optional .tutorial.TurnData turnData = 3;</code>
     */
    boolean hasTurnData();
    /**
     * <code>optional .tutorial.TurnData turnData = 3;</code>
     */
    org.sterl.proto.TestMessage.TurnData getTurnData();
    /**
     * <code>optional .tutorial.TurnData turnData = 3;</code>
     */
    org.sterl.proto.TestMessage.TurnDataOrBuilder getTurnDataOrBuilder();

    /**
     * <code>optional .tutorial.JumpData jumpData = 4;</code>
     */
    boolean hasJumpData();
    /**
     * <code>optional .tutorial.JumpData jumpData = 4;</code>
     */
    org.sterl.proto.TestMessage.JumpData getJumpData();
    /**
     * <code>optional .tutorial.JumpData jumpData = 4;</code>
     */
    org.sterl.proto.TestMessage.JumpDataOrBuilder getJumpDataOrBuilder();
  }
  /**
   * Protobuf type {@code tutorial.RequestMessage}
   */
  public static final class RequestMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tutorial.RequestMessage)
      RequestMessageOrBuilder {
    // Use RequestMessage.newBuilder() to construct.
    private RequestMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RequestMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RequestMessage defaultInstance;
    public static RequestMessage getDefaultInstance() {
      return defaultInstance;
    }

    public RequestMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RequestMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.sterl.proto.TestMessage.RequestMessage.MessageType value = org.sterl.proto.TestMessage.RequestMessage.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              org.sterl.proto.TestMessage.MoveData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = moveData_.toBuilder();
              }
              moveData_ = input.readMessage(org.sterl.proto.TestMessage.MoveData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(moveData_);
                moveData_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              org.sterl.proto.TestMessage.TurnData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = turnData_.toBuilder();
              }
              turnData_ = input.readMessage(org.sterl.proto.TestMessage.TurnData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(turnData_);
                turnData_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              org.sterl.proto.TestMessage.JumpData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = jumpData_.toBuilder();
              }
              jumpData_ = input.readMessage(org.sterl.proto.TestMessage.JumpData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(jumpData_);
                jumpData_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sterl.proto.TestMessage.internal_static_tutorial_RequestMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sterl.proto.TestMessage.internal_static_tutorial_RequestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sterl.proto.TestMessage.RequestMessage.class, org.sterl.proto.TestMessage.RequestMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<RequestMessage> PARSER =
        new com.google.protobuf.AbstractParser<RequestMessage>() {
      public RequestMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RequestMessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code tutorial.RequestMessage.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MOVE = 0;</code>
       */
      MOVE(0, 0),
      /**
       * <code>STOP = 1;</code>
       */
      STOP(1, 1),
      /**
       * <code>TURN = 2;</code>
       */
      TURN(2, 2),
      /**
       * <code>JUMP = 3;</code>
       */
      JUMP(3, 3),
      ;

      /**
       * <code>MOVE = 0;</code>
       */
      public static final int MOVE_VALUE = 0;
      /**
       * <code>STOP = 1;</code>
       */
      public static final int STOP_VALUE = 1;
      /**
       * <code>TURN = 2;</code>
       */
      public static final int TURN_VALUE = 2;
      /**
       * <code>JUMP = 3;</code>
       */
      public static final int JUMP_VALUE = 3;


      public final int getNumber() { return value; }

      public static MessageType valueOf(int value) {
        switch (value) {
          case 0: return MOVE;
          case 1: return STOP;
          case 2: return TURN;
          case 3: return JUMP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.sterl.proto.TestMessage.RequestMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tutorial.RequestMessage.MessageType)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private org.sterl.proto.TestMessage.RequestMessage.MessageType type_;
    /**
     * <code>required .tutorial.RequestMessage.MessageType type = 1 [default = MOVE];</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .tutorial.RequestMessage.MessageType type = 1 [default = MOVE];</code>
     */
    public org.sterl.proto.TestMessage.RequestMessage.MessageType getType() {
      return type_;
    }

    public static final int MOVEDATA_FIELD_NUMBER = 2;
    private org.sterl.proto.TestMessage.MoveData moveData_;
    /**
     * <code>optional .tutorial.MoveData moveData = 2;</code>
     */
    public boolean hasMoveData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .tutorial.MoveData moveData = 2;</code>
     */
    public org.sterl.proto.TestMessage.MoveData getMoveData() {
      return moveData_;
    }
    /**
     * <code>optional .tutorial.MoveData moveData = 2;</code>
     */
    public org.sterl.proto.TestMessage.MoveDataOrBuilder getMoveDataOrBuilder() {
      return moveData_;
    }

    public static final int TURNDATA_FIELD_NUMBER = 3;
    private org.sterl.proto.TestMessage.TurnData turnData_;
    /**
     * <code>optional .tutorial.TurnData turnData = 3;</code>
     */
    public boolean hasTurnData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .tutorial.TurnData turnData = 3;</code>
     */
    public org.sterl.proto.TestMessage.TurnData getTurnData() {
      return turnData_;
    }
    /**
     * <code>optional .tutorial.TurnData turnData = 3;</code>
     */
    public org.sterl.proto.TestMessage.TurnDataOrBuilder getTurnDataOrBuilder() {
      return turnData_;
    }

    public static final int JUMPDATA_FIELD_NUMBER = 4;
    private org.sterl.proto.TestMessage.JumpData jumpData_;
    /**
     * <code>optional .tutorial.JumpData jumpData = 4;</code>
     */
    public boolean hasJumpData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .tutorial.JumpData jumpData = 4;</code>
     */
    public org.sterl.proto.TestMessage.JumpData getJumpData() {
      return jumpData_;
    }
    /**
     * <code>optional .tutorial.JumpData jumpData = 4;</code>
     */
    public org.sterl.proto.TestMessage.JumpDataOrBuilder getJumpDataOrBuilder() {
      return jumpData_;
    }

    private void initFields() {
      type_ = org.sterl.proto.TestMessage.RequestMessage.MessageType.MOVE;
      moveData_ = org.sterl.proto.TestMessage.MoveData.getDefaultInstance();
      turnData_ = org.sterl.proto.TestMessage.TurnData.getDefaultInstance();
      jumpData_ = org.sterl.proto.TestMessage.JumpData.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasMoveData()) {
        if (!getMoveData().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasTurnData()) {
        if (!getTurnData().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasJumpData()) {
        if (!getJumpData().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, moveData_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, turnData_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, jumpData_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, moveData_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, turnData_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, jumpData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.sterl.proto.TestMessage.RequestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sterl.proto.TestMessage.RequestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sterl.proto.TestMessage.RequestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sterl.proto.TestMessage.RequestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sterl.proto.TestMessage.RequestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.sterl.proto.TestMessage.RequestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.sterl.proto.TestMessage.RequestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.sterl.proto.TestMessage.RequestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.sterl.proto.TestMessage.RequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.sterl.proto.TestMessage.RequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.sterl.proto.TestMessage.RequestMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.RequestMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.RequestMessage)
        org.sterl.proto.TestMessage.RequestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sterl.proto.TestMessage.internal_static_tutorial_RequestMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sterl.proto.TestMessage.internal_static_tutorial_RequestMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.sterl.proto.TestMessage.RequestMessage.class, org.sterl.proto.TestMessage.RequestMessage.Builder.class);
      }

      // Construct using org.sterl.proto.TestMessage.RequestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMoveDataFieldBuilder();
          getTurnDataFieldBuilder();
          getJumpDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = org.sterl.proto.TestMessage.RequestMessage.MessageType.MOVE;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (moveDataBuilder_ == null) {
          moveData_ = org.sterl.proto.TestMessage.MoveData.getDefaultInstance();
        } else {
          moveDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (turnDataBuilder_ == null) {
          turnData_ = org.sterl.proto.TestMessage.TurnData.getDefaultInstance();
        } else {
          turnDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (jumpDataBuilder_ == null) {
          jumpData_ = org.sterl.proto.TestMessage.JumpData.getDefaultInstance();
        } else {
          jumpDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sterl.proto.TestMessage.internal_static_tutorial_RequestMessage_descriptor;
      }

      public org.sterl.proto.TestMessage.RequestMessage getDefaultInstanceForType() {
        return org.sterl.proto.TestMessage.RequestMessage.getDefaultInstance();
      }

      public org.sterl.proto.TestMessage.RequestMessage build() {
        org.sterl.proto.TestMessage.RequestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.sterl.proto.TestMessage.RequestMessage buildPartial() {
        org.sterl.proto.TestMessage.RequestMessage result = new org.sterl.proto.TestMessage.RequestMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (moveDataBuilder_ == null) {
          result.moveData_ = moveData_;
        } else {
          result.moveData_ = moveDataBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (turnDataBuilder_ == null) {
          result.turnData_ = turnData_;
        } else {
          result.turnData_ = turnDataBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (jumpDataBuilder_ == null) {
          result.jumpData_ = jumpData_;
        } else {
          result.jumpData_ = jumpDataBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sterl.proto.TestMessage.RequestMessage) {
          return mergeFrom((org.sterl.proto.TestMessage.RequestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.sterl.proto.TestMessage.RequestMessage other) {
        if (other == org.sterl.proto.TestMessage.RequestMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasMoveData()) {
          mergeMoveData(other.getMoveData());
        }
        if (other.hasTurnData()) {
          mergeTurnData(other.getTurnData());
        }
        if (other.hasJumpData()) {
          mergeJumpData(other.getJumpData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasMoveData()) {
          if (!getMoveData().isInitialized()) {
            
            return false;
          }
        }
        if (hasTurnData()) {
          if (!getTurnData().isInitialized()) {
            
            return false;
          }
        }
        if (hasJumpData()) {
          if (!getJumpData().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.sterl.proto.TestMessage.RequestMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.sterl.proto.TestMessage.RequestMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private org.sterl.proto.TestMessage.RequestMessage.MessageType type_ = org.sterl.proto.TestMessage.RequestMessage.MessageType.MOVE;
      /**
       * <code>required .tutorial.RequestMessage.MessageType type = 1 [default = MOVE];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .tutorial.RequestMessage.MessageType type = 1 [default = MOVE];</code>
       */
      public org.sterl.proto.TestMessage.RequestMessage.MessageType getType() {
        return type_;
      }
      /**
       * <code>required .tutorial.RequestMessage.MessageType type = 1 [default = MOVE];</code>
       */
      public Builder setType(org.sterl.proto.TestMessage.RequestMessage.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .tutorial.RequestMessage.MessageType type = 1 [default = MOVE];</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = org.sterl.proto.TestMessage.RequestMessage.MessageType.MOVE;
        onChanged();
        return this;
      }

      private org.sterl.proto.TestMessage.MoveData moveData_ = org.sterl.proto.TestMessage.MoveData.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.sterl.proto.TestMessage.MoveData, org.sterl.proto.TestMessage.MoveData.Builder, org.sterl.proto.TestMessage.MoveDataOrBuilder> moveDataBuilder_;
      /**
       * <code>optional .tutorial.MoveData moveData = 2;</code>
       */
      public boolean hasMoveData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .tutorial.MoveData moveData = 2;</code>
       */
      public org.sterl.proto.TestMessage.MoveData getMoveData() {
        if (moveDataBuilder_ == null) {
          return moveData_;
        } else {
          return moveDataBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .tutorial.MoveData moveData = 2;</code>
       */
      public Builder setMoveData(org.sterl.proto.TestMessage.MoveData value) {
        if (moveDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          moveData_ = value;
          onChanged();
        } else {
          moveDataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .tutorial.MoveData moveData = 2;</code>
       */
      public Builder setMoveData(
          org.sterl.proto.TestMessage.MoveData.Builder builderForValue) {
        if (moveDataBuilder_ == null) {
          moveData_ = builderForValue.build();
          onChanged();
        } else {
          moveDataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .tutorial.MoveData moveData = 2;</code>
       */
      public Builder mergeMoveData(org.sterl.proto.TestMessage.MoveData value) {
        if (moveDataBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              moveData_ != org.sterl.proto.TestMessage.MoveData.getDefaultInstance()) {
            moveData_ =
              org.sterl.proto.TestMessage.MoveData.newBuilder(moveData_).mergeFrom(value).buildPartial();
          } else {
            moveData_ = value;
          }
          onChanged();
        } else {
          moveDataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .tutorial.MoveData moveData = 2;</code>
       */
      public Builder clearMoveData() {
        if (moveDataBuilder_ == null) {
          moveData_ = org.sterl.proto.TestMessage.MoveData.getDefaultInstance();
          onChanged();
        } else {
          moveDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .tutorial.MoveData moveData = 2;</code>
       */
      public org.sterl.proto.TestMessage.MoveData.Builder getMoveDataBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getMoveDataFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .tutorial.MoveData moveData = 2;</code>
       */
      public org.sterl.proto.TestMessage.MoveDataOrBuilder getMoveDataOrBuilder() {
        if (moveDataBuilder_ != null) {
          return moveDataBuilder_.getMessageOrBuilder();
        } else {
          return moveData_;
        }
      }
      /**
       * <code>optional .tutorial.MoveData moveData = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.sterl.proto.TestMessage.MoveData, org.sterl.proto.TestMessage.MoveData.Builder, org.sterl.proto.TestMessage.MoveDataOrBuilder> 
          getMoveDataFieldBuilder() {
        if (moveDataBuilder_ == null) {
          moveDataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.sterl.proto.TestMessage.MoveData, org.sterl.proto.TestMessage.MoveData.Builder, org.sterl.proto.TestMessage.MoveDataOrBuilder>(
                  getMoveData(),
                  getParentForChildren(),
                  isClean());
          moveData_ = null;
        }
        return moveDataBuilder_;
      }

      private org.sterl.proto.TestMessage.TurnData turnData_ = org.sterl.proto.TestMessage.TurnData.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.sterl.proto.TestMessage.TurnData, org.sterl.proto.TestMessage.TurnData.Builder, org.sterl.proto.TestMessage.TurnDataOrBuilder> turnDataBuilder_;
      /**
       * <code>optional .tutorial.TurnData turnData = 3;</code>
       */
      public boolean hasTurnData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .tutorial.TurnData turnData = 3;</code>
       */
      public org.sterl.proto.TestMessage.TurnData getTurnData() {
        if (turnDataBuilder_ == null) {
          return turnData_;
        } else {
          return turnDataBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .tutorial.TurnData turnData = 3;</code>
       */
      public Builder setTurnData(org.sterl.proto.TestMessage.TurnData value) {
        if (turnDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          turnData_ = value;
          onChanged();
        } else {
          turnDataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .tutorial.TurnData turnData = 3;</code>
       */
      public Builder setTurnData(
          org.sterl.proto.TestMessage.TurnData.Builder builderForValue) {
        if (turnDataBuilder_ == null) {
          turnData_ = builderForValue.build();
          onChanged();
        } else {
          turnDataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .tutorial.TurnData turnData = 3;</code>
       */
      public Builder mergeTurnData(org.sterl.proto.TestMessage.TurnData value) {
        if (turnDataBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              turnData_ != org.sterl.proto.TestMessage.TurnData.getDefaultInstance()) {
            turnData_ =
              org.sterl.proto.TestMessage.TurnData.newBuilder(turnData_).mergeFrom(value).buildPartial();
          } else {
            turnData_ = value;
          }
          onChanged();
        } else {
          turnDataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .tutorial.TurnData turnData = 3;</code>
       */
      public Builder clearTurnData() {
        if (turnDataBuilder_ == null) {
          turnData_ = org.sterl.proto.TestMessage.TurnData.getDefaultInstance();
          onChanged();
        } else {
          turnDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .tutorial.TurnData turnData = 3;</code>
       */
      public org.sterl.proto.TestMessage.TurnData.Builder getTurnDataBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getTurnDataFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .tutorial.TurnData turnData = 3;</code>
       */
      public org.sterl.proto.TestMessage.TurnDataOrBuilder getTurnDataOrBuilder() {
        if (turnDataBuilder_ != null) {
          return turnDataBuilder_.getMessageOrBuilder();
        } else {
          return turnData_;
        }
      }
      /**
       * <code>optional .tutorial.TurnData turnData = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.sterl.proto.TestMessage.TurnData, org.sterl.proto.TestMessage.TurnData.Builder, org.sterl.proto.TestMessage.TurnDataOrBuilder> 
          getTurnDataFieldBuilder() {
        if (turnDataBuilder_ == null) {
          turnDataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.sterl.proto.TestMessage.TurnData, org.sterl.proto.TestMessage.TurnData.Builder, org.sterl.proto.TestMessage.TurnDataOrBuilder>(
                  getTurnData(),
                  getParentForChildren(),
                  isClean());
          turnData_ = null;
        }
        return turnDataBuilder_;
      }

      private org.sterl.proto.TestMessage.JumpData jumpData_ = org.sterl.proto.TestMessage.JumpData.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.sterl.proto.TestMessage.JumpData, org.sterl.proto.TestMessage.JumpData.Builder, org.sterl.proto.TestMessage.JumpDataOrBuilder> jumpDataBuilder_;
      /**
       * <code>optional .tutorial.JumpData jumpData = 4;</code>
       */
      public boolean hasJumpData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .tutorial.JumpData jumpData = 4;</code>
       */
      public org.sterl.proto.TestMessage.JumpData getJumpData() {
        if (jumpDataBuilder_ == null) {
          return jumpData_;
        } else {
          return jumpDataBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .tutorial.JumpData jumpData = 4;</code>
       */
      public Builder setJumpData(org.sterl.proto.TestMessage.JumpData value) {
        if (jumpDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          jumpData_ = value;
          onChanged();
        } else {
          jumpDataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .tutorial.JumpData jumpData = 4;</code>
       */
      public Builder setJumpData(
          org.sterl.proto.TestMessage.JumpData.Builder builderForValue) {
        if (jumpDataBuilder_ == null) {
          jumpData_ = builderForValue.build();
          onChanged();
        } else {
          jumpDataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .tutorial.JumpData jumpData = 4;</code>
       */
      public Builder mergeJumpData(org.sterl.proto.TestMessage.JumpData value) {
        if (jumpDataBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              jumpData_ != org.sterl.proto.TestMessage.JumpData.getDefaultInstance()) {
            jumpData_ =
              org.sterl.proto.TestMessage.JumpData.newBuilder(jumpData_).mergeFrom(value).buildPartial();
          } else {
            jumpData_ = value;
          }
          onChanged();
        } else {
          jumpDataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .tutorial.JumpData jumpData = 4;</code>
       */
      public Builder clearJumpData() {
        if (jumpDataBuilder_ == null) {
          jumpData_ = org.sterl.proto.TestMessage.JumpData.getDefaultInstance();
          onChanged();
        } else {
          jumpDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .tutorial.JumpData jumpData = 4;</code>
       */
      public org.sterl.proto.TestMessage.JumpData.Builder getJumpDataBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getJumpDataFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .tutorial.JumpData jumpData = 4;</code>
       */
      public org.sterl.proto.TestMessage.JumpDataOrBuilder getJumpDataOrBuilder() {
        if (jumpDataBuilder_ != null) {
          return jumpDataBuilder_.getMessageOrBuilder();
        } else {
          return jumpData_;
        }
      }
      /**
       * <code>optional .tutorial.JumpData jumpData = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.sterl.proto.TestMessage.JumpData, org.sterl.proto.TestMessage.JumpData.Builder, org.sterl.proto.TestMessage.JumpDataOrBuilder> 
          getJumpDataFieldBuilder() {
        if (jumpDataBuilder_ == null) {
          jumpDataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.sterl.proto.TestMessage.JumpData, org.sterl.proto.TestMessage.JumpData.Builder, org.sterl.proto.TestMessage.JumpDataOrBuilder>(
                  getJumpData(),
                  getParentForChildren(),
                  isClean());
          jumpData_ = null;
        }
        return jumpDataBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.RequestMessage)
    }

    static {
      defaultInstance = new RequestMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.RequestMessage)
  }

  public interface MoveDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.MoveData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 speed = 1 [default = 500];</code>
     *
     * <pre>
     * how fast the move
     * </pre>
     */
    boolean hasSpeed();
    /**
     * <code>required int32 speed = 1 [default = 500];</code>
     *
     * <pre>
     * how fast the move
     * </pre>
     */
    int getSpeed();
  }
  /**
   * Protobuf type {@code tutorial.MoveData}
   *
   * <pre>
   * movement data
   * </pre>
   */
  public static final class MoveData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tutorial.MoveData)
      MoveDataOrBuilder {
    // Use MoveData.newBuilder() to construct.
    private MoveData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MoveData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MoveData defaultInstance;
    public static MoveData getDefaultInstance() {
      return defaultInstance;
    }

    public MoveData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MoveData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              speed_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sterl.proto.TestMessage.internal_static_tutorial_MoveData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sterl.proto.TestMessage.internal_static_tutorial_MoveData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sterl.proto.TestMessage.MoveData.class, org.sterl.proto.TestMessage.MoveData.Builder.class);
    }

    public static com.google.protobuf.Parser<MoveData> PARSER =
        new com.google.protobuf.AbstractParser<MoveData>() {
      public MoveData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MoveData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MoveData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SPEED_FIELD_NUMBER = 1;
    private int speed_;
    /**
     * <code>required int32 speed = 1 [default = 500];</code>
     *
     * <pre>
     * how fast the move
     * </pre>
     */
    public boolean hasSpeed() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 speed = 1 [default = 500];</code>
     *
     * <pre>
     * how fast the move
     * </pre>
     */
    public int getSpeed() {
      return speed_;
    }

    private void initFields() {
      speed_ = 500;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSpeed()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, speed_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, speed_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.sterl.proto.TestMessage.MoveData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sterl.proto.TestMessage.MoveData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sterl.proto.TestMessage.MoveData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sterl.proto.TestMessage.MoveData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sterl.proto.TestMessage.MoveData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.sterl.proto.TestMessage.MoveData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.sterl.proto.TestMessage.MoveData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.sterl.proto.TestMessage.MoveData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.sterl.proto.TestMessage.MoveData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.sterl.proto.TestMessage.MoveData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.sterl.proto.TestMessage.MoveData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.MoveData}
     *
     * <pre>
     * movement data
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.MoveData)
        org.sterl.proto.TestMessage.MoveDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sterl.proto.TestMessage.internal_static_tutorial_MoveData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sterl.proto.TestMessage.internal_static_tutorial_MoveData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.sterl.proto.TestMessage.MoveData.class, org.sterl.proto.TestMessage.MoveData.Builder.class);
      }

      // Construct using org.sterl.proto.TestMessage.MoveData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        speed_ = 500;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sterl.proto.TestMessage.internal_static_tutorial_MoveData_descriptor;
      }

      public org.sterl.proto.TestMessage.MoveData getDefaultInstanceForType() {
        return org.sterl.proto.TestMessage.MoveData.getDefaultInstance();
      }

      public org.sterl.proto.TestMessage.MoveData build() {
        org.sterl.proto.TestMessage.MoveData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.sterl.proto.TestMessage.MoveData buildPartial() {
        org.sterl.proto.TestMessage.MoveData result = new org.sterl.proto.TestMessage.MoveData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.speed_ = speed_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sterl.proto.TestMessage.MoveData) {
          return mergeFrom((org.sterl.proto.TestMessage.MoveData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.sterl.proto.TestMessage.MoveData other) {
        if (other == org.sterl.proto.TestMessage.MoveData.getDefaultInstance()) return this;
        if (other.hasSpeed()) {
          setSpeed(other.getSpeed());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSpeed()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.sterl.proto.TestMessage.MoveData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.sterl.proto.TestMessage.MoveData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int speed_ = 500;
      /**
       * <code>required int32 speed = 1 [default = 500];</code>
       *
       * <pre>
       * how fast the move
       * </pre>
       */
      public boolean hasSpeed() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 speed = 1 [default = 500];</code>
       *
       * <pre>
       * how fast the move
       * </pre>
       */
      public int getSpeed() {
        return speed_;
      }
      /**
       * <code>required int32 speed = 1 [default = 500];</code>
       *
       * <pre>
       * how fast the move
       * </pre>
       */
      public Builder setSpeed(int value) {
        bitField0_ |= 0x00000001;
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 speed = 1 [default = 500];</code>
       *
       * <pre>
       * how fast the move
       * </pre>
       */
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00000001);
        speed_ = 500;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.MoveData)
    }

    static {
      defaultInstance = new MoveData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.MoveData)
  }

  public interface TurnDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.TurnData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 angle = 1 [default = 90];</code>
     *
     * <pre>
     * the angle to do
     * </pre>
     */
    boolean hasAngle();
    /**
     * <code>required int32 angle = 1 [default = 90];</code>
     *
     * <pre>
     * the angle to do
     * </pre>
     */
    int getAngle();
  }
  /**
   * Protobuf type {@code tutorial.TurnData}
   *
   * <pre>
   * turn data
   * </pre>
   */
  public static final class TurnData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tutorial.TurnData)
      TurnDataOrBuilder {
    // Use TurnData.newBuilder() to construct.
    private TurnData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TurnData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TurnData defaultInstance;
    public static TurnData getDefaultInstance() {
      return defaultInstance;
    }

    public TurnData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TurnData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              angle_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sterl.proto.TestMessage.internal_static_tutorial_TurnData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sterl.proto.TestMessage.internal_static_tutorial_TurnData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sterl.proto.TestMessage.TurnData.class, org.sterl.proto.TestMessage.TurnData.Builder.class);
    }

    public static com.google.protobuf.Parser<TurnData> PARSER =
        new com.google.protobuf.AbstractParser<TurnData>() {
      public TurnData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TurnData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TurnData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ANGLE_FIELD_NUMBER = 1;
    private int angle_;
    /**
     * <code>required int32 angle = 1 [default = 90];</code>
     *
     * <pre>
     * the angle to do
     * </pre>
     */
    public boolean hasAngle() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 angle = 1 [default = 90];</code>
     *
     * <pre>
     * the angle to do
     * </pre>
     */
    public int getAngle() {
      return angle_;
    }

    private void initFields() {
      angle_ = 90;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAngle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, angle_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, angle_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.sterl.proto.TestMessage.TurnData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sterl.proto.TestMessage.TurnData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sterl.proto.TestMessage.TurnData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sterl.proto.TestMessage.TurnData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sterl.proto.TestMessage.TurnData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.sterl.proto.TestMessage.TurnData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.sterl.proto.TestMessage.TurnData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.sterl.proto.TestMessage.TurnData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.sterl.proto.TestMessage.TurnData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.sterl.proto.TestMessage.TurnData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.sterl.proto.TestMessage.TurnData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.TurnData}
     *
     * <pre>
     * turn data
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.TurnData)
        org.sterl.proto.TestMessage.TurnDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sterl.proto.TestMessage.internal_static_tutorial_TurnData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sterl.proto.TestMessage.internal_static_tutorial_TurnData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.sterl.proto.TestMessage.TurnData.class, org.sterl.proto.TestMessage.TurnData.Builder.class);
      }

      // Construct using org.sterl.proto.TestMessage.TurnData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        angle_ = 90;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sterl.proto.TestMessage.internal_static_tutorial_TurnData_descriptor;
      }

      public org.sterl.proto.TestMessage.TurnData getDefaultInstanceForType() {
        return org.sterl.proto.TestMessage.TurnData.getDefaultInstance();
      }

      public org.sterl.proto.TestMessage.TurnData build() {
        org.sterl.proto.TestMessage.TurnData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.sterl.proto.TestMessage.TurnData buildPartial() {
        org.sterl.proto.TestMessage.TurnData result = new org.sterl.proto.TestMessage.TurnData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.angle_ = angle_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sterl.proto.TestMessage.TurnData) {
          return mergeFrom((org.sterl.proto.TestMessage.TurnData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.sterl.proto.TestMessage.TurnData other) {
        if (other == org.sterl.proto.TestMessage.TurnData.getDefaultInstance()) return this;
        if (other.hasAngle()) {
          setAngle(other.getAngle());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAngle()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.sterl.proto.TestMessage.TurnData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.sterl.proto.TestMessage.TurnData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int angle_ = 90;
      /**
       * <code>required int32 angle = 1 [default = 90];</code>
       *
       * <pre>
       * the angle to do
       * </pre>
       */
      public boolean hasAngle() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 angle = 1 [default = 90];</code>
       *
       * <pre>
       * the angle to do
       * </pre>
       */
      public int getAngle() {
        return angle_;
      }
      /**
       * <code>required int32 angle = 1 [default = 90];</code>
       *
       * <pre>
       * the angle to do
       * </pre>
       */
      public Builder setAngle(int value) {
        bitField0_ |= 0x00000001;
        angle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 angle = 1 [default = 90];</code>
       *
       * <pre>
       * the angle to do
       * </pre>
       */
      public Builder clearAngle() {
        bitField0_ = (bitField0_ & ~0x00000001);
        angle_ = 90;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.TurnData)
    }

    static {
      defaultInstance = new TurnData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.TurnData)
  }

  public interface JumpDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.JumpData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 howHigh = 1 [default = 10];</code>
     *
     * <pre>
     * how high in cm
     * </pre>
     */
    boolean hasHowHigh();
    /**
     * <code>required int32 howHigh = 1 [default = 10];</code>
     *
     * <pre>
     * how high in cm
     * </pre>
     */
    int getHowHigh();

    /**
     * <code>required int32 howFar = 2 [default = 10];</code>
     *
     * <pre>
     * how far in cm
     * </pre>
     */
    boolean hasHowFar();
    /**
     * <code>required int32 howFar = 2 [default = 10];</code>
     *
     * <pre>
     * how far in cm
     * </pre>
     */
    int getHowFar();
  }
  /**
   * Protobuf type {@code tutorial.JumpData}
   */
  public static final class JumpData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tutorial.JumpData)
      JumpDataOrBuilder {
    // Use JumpData.newBuilder() to construct.
    private JumpData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private JumpData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final JumpData defaultInstance;
    public static JumpData getDefaultInstance() {
      return defaultInstance;
    }

    public JumpData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private JumpData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              howHigh_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              howFar_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sterl.proto.TestMessage.internal_static_tutorial_JumpData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sterl.proto.TestMessage.internal_static_tutorial_JumpData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sterl.proto.TestMessage.JumpData.class, org.sterl.proto.TestMessage.JumpData.Builder.class);
    }

    public static com.google.protobuf.Parser<JumpData> PARSER =
        new com.google.protobuf.AbstractParser<JumpData>() {
      public JumpData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JumpData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<JumpData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int HOWHIGH_FIELD_NUMBER = 1;
    private int howHigh_;
    /**
     * <code>required int32 howHigh = 1 [default = 10];</code>
     *
     * <pre>
     * how high in cm
     * </pre>
     */
    public boolean hasHowHigh() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 howHigh = 1 [default = 10];</code>
     *
     * <pre>
     * how high in cm
     * </pre>
     */
    public int getHowHigh() {
      return howHigh_;
    }

    public static final int HOWFAR_FIELD_NUMBER = 2;
    private int howFar_;
    /**
     * <code>required int32 howFar = 2 [default = 10];</code>
     *
     * <pre>
     * how far in cm
     * </pre>
     */
    public boolean hasHowFar() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 howFar = 2 [default = 10];</code>
     *
     * <pre>
     * how far in cm
     * </pre>
     */
    public int getHowFar() {
      return howFar_;
    }

    private void initFields() {
      howHigh_ = 10;
      howFar_ = 10;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHowHigh()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHowFar()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, howHigh_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, howFar_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, howHigh_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, howFar_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.sterl.proto.TestMessage.JumpData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sterl.proto.TestMessage.JumpData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sterl.proto.TestMessage.JumpData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sterl.proto.TestMessage.JumpData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sterl.proto.TestMessage.JumpData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.sterl.proto.TestMessage.JumpData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.sterl.proto.TestMessage.JumpData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.sterl.proto.TestMessage.JumpData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.sterl.proto.TestMessage.JumpData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.sterl.proto.TestMessage.JumpData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.sterl.proto.TestMessage.JumpData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.JumpData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.JumpData)
        org.sterl.proto.TestMessage.JumpDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sterl.proto.TestMessage.internal_static_tutorial_JumpData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sterl.proto.TestMessage.internal_static_tutorial_JumpData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.sterl.proto.TestMessage.JumpData.class, org.sterl.proto.TestMessage.JumpData.Builder.class);
      }

      // Construct using org.sterl.proto.TestMessage.JumpData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        howHigh_ = 10;
        bitField0_ = (bitField0_ & ~0x00000001);
        howFar_ = 10;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sterl.proto.TestMessage.internal_static_tutorial_JumpData_descriptor;
      }

      public org.sterl.proto.TestMessage.JumpData getDefaultInstanceForType() {
        return org.sterl.proto.TestMessage.JumpData.getDefaultInstance();
      }

      public org.sterl.proto.TestMessage.JumpData build() {
        org.sterl.proto.TestMessage.JumpData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.sterl.proto.TestMessage.JumpData buildPartial() {
        org.sterl.proto.TestMessage.JumpData result = new org.sterl.proto.TestMessage.JumpData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.howHigh_ = howHigh_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.howFar_ = howFar_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sterl.proto.TestMessage.JumpData) {
          return mergeFrom((org.sterl.proto.TestMessage.JumpData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.sterl.proto.TestMessage.JumpData other) {
        if (other == org.sterl.proto.TestMessage.JumpData.getDefaultInstance()) return this;
        if (other.hasHowHigh()) {
          setHowHigh(other.getHowHigh());
        }
        if (other.hasHowFar()) {
          setHowFar(other.getHowFar());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHowHigh()) {
          
          return false;
        }
        if (!hasHowFar()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.sterl.proto.TestMessage.JumpData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.sterl.proto.TestMessage.JumpData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int howHigh_ = 10;
      /**
       * <code>required int32 howHigh = 1 [default = 10];</code>
       *
       * <pre>
       * how high in cm
       * </pre>
       */
      public boolean hasHowHigh() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 howHigh = 1 [default = 10];</code>
       *
       * <pre>
       * how high in cm
       * </pre>
       */
      public int getHowHigh() {
        return howHigh_;
      }
      /**
       * <code>required int32 howHigh = 1 [default = 10];</code>
       *
       * <pre>
       * how high in cm
       * </pre>
       */
      public Builder setHowHigh(int value) {
        bitField0_ |= 0x00000001;
        howHigh_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 howHigh = 1 [default = 10];</code>
       *
       * <pre>
       * how high in cm
       * </pre>
       */
      public Builder clearHowHigh() {
        bitField0_ = (bitField0_ & ~0x00000001);
        howHigh_ = 10;
        onChanged();
        return this;
      }

      private int howFar_ = 10;
      /**
       * <code>required int32 howFar = 2 [default = 10];</code>
       *
       * <pre>
       * how far in cm
       * </pre>
       */
      public boolean hasHowFar() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 howFar = 2 [default = 10];</code>
       *
       * <pre>
       * how far in cm
       * </pre>
       */
      public int getHowFar() {
        return howFar_;
      }
      /**
       * <code>required int32 howFar = 2 [default = 10];</code>
       *
       * <pre>
       * how far in cm
       * </pre>
       */
      public Builder setHowFar(int value) {
        bitField0_ |= 0x00000002;
        howFar_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 howFar = 2 [default = 10];</code>
       *
       * <pre>
       * how far in cm
       * </pre>
       */
      public Builder clearHowFar() {
        bitField0_ = (bitField0_ & ~0x00000002);
        howFar_ = 10;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.JumpData)
    }

    static {
      defaultInstance = new JumpData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.JumpData)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_RequestMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_RequestMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_MoveData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_MoveData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_TurnData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_TurnData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_JumpData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_JumpData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!main/resources/test_message.proto\022\010tut" +
      "orial\"\363\001\n\016RequestMessage\0228\n\004type\030\001 \002(\0162$" +
      ".tutorial.RequestMessage.MessageType:\004MO" +
      "VE\022$\n\010moveData\030\002 \001(\0132\022.tutorial.MoveData" +
      "\022$\n\010turnData\030\003 \001(\0132\022.tutorial.TurnData\022$" +
      "\n\010jumpData\030\004 \001(\0132\022.tutorial.JumpData\"5\n\013" +
      "MessageType\022\010\n\004MOVE\020\000\022\010\n\004STOP\020\001\022\010\n\004TURN\020" +
      "\002\022\010\n\004JUMP\020\003\"\036\n\010MoveData\022\022\n\005speed\030\001 \002(\005:\003" +
      "500\"\035\n\010TurnData\022\021\n\005angle\030\001 \002(\005:\00290\"3\n\010Ju" +
      "mpData\022\023\n\007howHigh\030\001 \002(\005:\00210\022\022\n\006howFar\030\002 ",
      "\002(\005:\00210B\021\n\017org.sterl.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tutorial_RequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_RequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tutorial_RequestMessage_descriptor,
        new java.lang.String[] { "Type", "MoveData", "TurnData", "JumpData", });
    internal_static_tutorial_MoveData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_MoveData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tutorial_MoveData_descriptor,
        new java.lang.String[] { "Speed", });
    internal_static_tutorial_TurnData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tutorial_TurnData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tutorial_TurnData_descriptor,
        new java.lang.String[] { "Angle", });
    internal_static_tutorial_JumpData_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tutorial_JumpData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tutorial_JumpData_descriptor,
        new java.lang.String[] { "HowHigh", "HowFar", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
