// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Users/sterlp/dev/workset/training/protocol-buffers/src/main/resources/wire_message.proto at 20:1
package org.sterl.wire;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;

/**
 * movement data
 */
public final class MoveData extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_SPEED = 500;

  /**
   * how fast the move
   */
  @ProtoField(
      tag = 1,
      type = Message.Datatype.INT32,
      label = Message.Label.REQUIRED
  )
  public final Integer speed;

  public MoveData(Integer speed) {
    this.speed = speed;
  }

  private MoveData(Builder builder) {
    this(builder.speed);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof MoveData)) return false;
    return equals(speed, ((MoveData) other).speed);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = speed != null ? speed.hashCode() : 0);
  }

  public static final class Builder extends com.squareup.wire.Message.Builder<MoveData> {
    public Integer speed;

    public Builder() {
    }

    public Builder(MoveData message) {
      super(message);
      if (message == null) return;
      this.speed = message.speed;
    }

    /**
     * how fast the move
     */
    public Builder speed(Integer speed) {
      this.speed = speed;
      return this;
    }

    @Override
    public MoveData build() {
      if (speed == null) {
        throw new RuntimeException(speed + "speed");
      }
      return new MoveData(this);
    }
  }
}
